version: '3.8'
services:
  app:
    build:
      context: ./frontend
      dockerfile: dev.Dockerfile
    ports:
      - 3000:3000
    volumes:
      - ./frontend:/app
    environment:
      - REACT_APP_API_URL=http://backend:3001
    depends_on:
      - server
  
  db:
    image: postgres
    container_name: postgres_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: messages_db
    ports:
      - 5432:5432
    volumes:
      - db_data:/var/lib/postgresql/data

  server:
    build:
      context: ./backend
      dockerfile: dev.Dockerfile
    ports:
      - 3001:3001
    volumes:
      - ./backend:/app
    environment:
      - DATABASE_URL=postgres://postgres:postgres@db:5432/messages_db
    depends_on:
      - db

  nginx:
    image: nginx:1.20.1
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - 8080:80
    container_name: reverse-proxy
    depends_on:
      - app
  
volumes:
  db_data: